version: '3.8'

services:

  backend:
    build: ./src
    ports:
      - 5000:5000
    environment:
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3ep
      - FRONTEND_HOST=${FRONTEND_HOST}
      - FRONTEND_PORT=${FRONTEND_PORT}
    volumes:
      - ./src:/app
      - ./static_volume:/app/static
    command: bash -c "python manage.py collectstatic --no-input --clear &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:5000"

  nginx:
    build: ./nginx
    ports:
      - ${FRONTEND_PORT}:80
    volumes:
      - ./nginx:/app
      - ./src/media:/app/media
      - ./static_volume:/app/static
    depends_on:
      - backend

volumes:
  static_volume:
  media_volume: